FROM node:15

WORKDIR /usr/src/app

RUN apt-get install -y wget

ENV DOCKERIZE_VERSION v0.7.0

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN npm init -y && \
    npm install express --save && \
    npm install mysql

COPY index.js .

EXPOSE 3000

# ENTRYPOINT [ "node", "index.js" ]